name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push
      run: dotnet nuget push "StringThings/bin/Release/*.nupkg" --source "nuget.org" --api-key ${{ secrets.NUGETPUSHANY }} --skip-duplicate
