name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal    
    - name: Pack
      if: success() && github.ref == 'refs/heads/master'    
      run: dotnet pack --configuration Release
    - name: Push
      if: success() && github.ref == 'refs/heads/master'    
      run: dotnet nuget push "StringThings/bin/Release/*.nupkg" --source "nuget.org" --api-key ${{ secrets.NUGETPUSHANY }} --skip-duplicate
